% http://www.ece.northwestern.edu/local-apps/matlabhelp/techdoc/ref/addpath.html
clear all
clear classes
addpath('/home/jessica/ATEMMA/MRI/Task/')
addpath('/home/jessica/ATEMMA/MRI/Task/2ndlevel/')
global dataDir;
mainDir = "/media/jessica/48243AC9243ABA30/IRM_Gaze/";
global resultDir;
resultDir = char(strcat(mainDir, 'results', '/'));
dataDir = char(strcat(mainDir, 'Files_ready', '/'));
cd(dataDir);
global categories;
categories = {'CN', 'YA'}; % remove AD for now

global spmdir;
spmdir = '/home/jessica/software/spm12/';

unauthorizedEye = ['PT19','CB05','RM01','VM09','RC01','PR02', 'DL26', 'LD13', 'MC11', 'BM24', 'GS23', 'PV49', 'VS719', 'SH27', 'FC03'];

nogaze = ['DL26', 'SH27', 'PT19', 'FC03'];

% firstLevelSpecificationResponse. We used
% firstLevelSpecificationClassicResponse in my thesis.
% No need to do contrasts in both sides
contrast_gaze_resp = {
    {'con_0003', 'Gaze-classic'},...
    {'con_0005', 'Fear'},...
    {'con_0006', 'Fear_classic'},...
    {'con_0007', 'Fear_gaze'},...
    {'con_0008', 'Angry'},...
    {'con_0009', 'Angry_classic'},...
    {'con_0010', 'Angry_gaze'},...
    {'con_0014', 'Emotion-Neutre'},...
    {'con_0015', 'Emotion-Neutre_classic'},...
    {'con_0016', 'Emotion-Neutre_gaze'},...
    {'con_0019', 'Fear-Neutre'},...
    {'con_0020', 'Fear-Neutre_classic'},...
    {'con_0021', 'Fear-Neutre_gaze'},...
    {'con_0022', 'Fear_gaze-Fear_classic'},...
    {'con_0024', 'Angry-Neutre'},...
    {'con_0025', 'Angry-Neutre_classic'},...
    {'con_0026', 'Angry-Neutre_gaze'},...
    {'con_0027', 'Angry_gaze-Angry_classic'},...
    {'con_0029', 'Inter_Neu_Emo_Gaze_Classic'},...
    {'con_0030', 'Inter_Fear_Neu_Gaze_Classic'},... % important
    {'con_0031', 'Inter_Angry_Neu_Gaze_Classic'},...
    };

% firstLevelSpecificationEye. We used firstLevelSpecificationClassicEye in
% my thesis.
contrast_gaze_eye = {
    {'con_0032', 'Increasing_first_time_eyes'},...
    {'con_0033', 'Increasing_first_time_eyes_classic'},...
    {'con_0034', 'Increasing_first_time_eyes_gaze'},...
    {'con_0035', 'Increasing_first_time_eyes_fear'},...
    {'con_0036', 'Increasing_first_time_eyes_fear_classic'},...
    {'con_0037', 'Increasing_first_time_eyes_fear_gaze'},...
    {'con_0038', 'Increasing_first_time_eyes_angry'},...
    {'con_0039', 'Increasing_first_time_eyes_angry_classic'},...
    {'con_0040', 'Increasing_first_time_eyes_angry_gaze'},...
    {'con_0044', 'Increasing_first_time_eyes_classic-gaze'},...
    {'con_0045', 'Increasing_first_time_eyes_gaze-classic'},...
    };

test = {
    {'con_0006', 'angry-neutre'}
    };

contrast_group(test, {}, 'testClassic', 'statsClassicResp')
contrast_group(contrast_gaze_resp, nogaze, 'GazeClassicResp', 'statsResp')
contrast_group(contrast_gaze_eye, unauthorizedEye, 'GazeClassicEye', 'statsEye')
